### ISSUE TITLE
Replacement for Teensy 3.2/LC for T61 keyboard?

### ISSUE THREAD

**Issue by ChoamCompany** [thedalles77/USB_Laptop_Keyboard_Controller#21]
Hello,

Just came across your project, I happened to place an order for a Teensy LC controller board, but then promptly canceled it after realizing the Teensy LC/3.2 are deprecated/out of stock, and have been replaced by the Teensy 4.0.

 Is there anything that needs to be done to use these newer Teensy boards with the files currently provided in the repository, and are there any special procedures for assembly/parts? 
 
 Given that neither the LC/3.2 are available anymore, which version of your controller board should I order?

Also, is the trackpoint able to work with the code currently published for the LC/3.2 on a Teensy 4.0? 

Thank you in advance.

**Comment by thedalles77** [comment]
Your timing is perfect. I've been updating my Instructable and GitHub repo to switch over to the Teensy 4.x due to the LC/3.2 going obsolete. I built a T61 keyboard/trackpoint/touchpad controller using a Teensy 4.0 a few days ago. The circuit board, code, and PDF files are [here](https://github.com/thedalles77/USB_Laptop_Keyboard_Controller/tree/master/Example_Keyboards/Lenovo_ThinkPad_T61/Teensy%204p0):
Let me know if you have any more questions.
