### ISSUE TITLE
PWR switch connection on T61 scanner

### ISSUE THREAD

**Issue by toonn** [thedalles77/USB_Laptop_Keyboard_Controller#4]
There's two connections on the Lenovo T61 scanner boards that I don't quite understand after reading through the Instructable, the T61 pdfs and the video.

Two through-holes for the caps lock LED, am I correct in assuming that they're to *mount* an LED in? My first assumption was there'd be an LED in the caps lock key.

There's one more hole marked "PWR switch", is this meant to connect to a device? To turn on the device using the keyboard's power button? If so, can this button be wired into the key matrix to use as an extra key if you have no use for a power button signal?

I'd like to thank you for the effort you've clearly spent on these instructions, I wouldn't feel capable of converting this keyboard without them! 💯 🎉 🥇

**Comment by thedalles77** [comment]
Toonn, sorry for not getting back sooner. The T61 code for the 3.2 and LC both send the Caps Lock status to Teensy I/O #13 which has a 3ma LED on the Teensy board. On my Teensy 3.2 T61 board, I just routed I/O #13 to the pad labeled "LED" so you can route it to your own LED that is visible when the keyboard and controller are in a case. You would need to include a dropping resistor in series with the LED, based on the current/voltage spec's of the LED. The Teensy 3.2 output can drive 25ma so a regular LED should work even with the 3ma LED in parallel on the Teensy. 
The Teensy LC also has an onboard 3ma LED but the Teensy LC chip can only output 5ma, leaving 2ma for an external LED (like the Digikey LED given in the PDF parts list). I included pads on my LC board for a 715 ohm dropping resistor that is in series with the "LED" connection pad. 
For both the 3.2 and LC boards, I included the PWR_SW connection pad so you could design a turn- on circuit that comes alive when the keyboard power switch is pushed. I hard wired the other side of the switch to ground, thinking you would use a pull up on the PWR_SW side of the switch and sense when the signal goes to ground. For the Teensy 3.2, you could solder a wire from the PWR_SW pad to an unused I/O pin, set the pin as an input with a pull up, and then write code outside of the normal key matrix code to watch for this input to go low. For the Teensy LC, this won't work because there are no spare I/O pins. 
Because I hard wired the power switch to ground, you can't wire it into the key matrix. I was able to put the Fn key on the LC board into the matrix because I didn't tie the Fn- side of the switch to ground so it could be driven low by the Teensy but floated when not activated.

Let me know if you have more questions. You'll get a quicker response if you send me an email at thedalles77@gmail.com
Cheers
